# Generated by Django 5.0.3 on 2024-03-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_dish_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_create_category', 'Can create categor')]},
        ),
    ]
